# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0009_auto_20161209_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='ticket_types', to='lan.TicketType'),
        ),
    ]
