# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0010_auto_20161202_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seating',
            options={'permissions': (('export_seating', 'Can export seating to downloadable file'),)},
        ),
    ]
