# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0012_auto_20190730_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seating', 'placement'], 'verbose_name': 'seat', 'verbose_name_plural': 'seats'},
        ),
    ]
