# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-04 16:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0014_seating_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='number_of_seats',
            field=models.IntegerField(default=0, editable=False, help_text='This field is automatically updated to match the chosen layout. Change the chosen layout to alter this field.', verbose_name='number of seats'),
        ),
    ]
