# Example Docker Compose config for Nginx reverse proxy and web server

# This example uses extarnal networks and static IPs, to make firewall and external Nginx config easier.

version: "2.4"
services:
  nginx-master:
    image: linuxserver/nginx
    container_name: nginx-master
    environment:
      # TODO add UID+GID of nginx host user
      - PUID=
      - PGID=
      - TZ=Europe/Oslo
    volumes:
      - /srv/nginx/config:/config/nginx:ro
      # TODO Add certs for all served domains, or use snakeoil ones temporarily
      #- /etc/ssl/certs/ssl-cert-snakeoil.pem:/config/keys/EXAMPLE.crt:ro
      #- /etc/ssl/private/ssl-cert-snakeoil.key:/config/keys/EXAMPLE.key:ro
      - /etc/letsencrypt/live/EXAMPLE/fullchain.pem:/config/keys/EXAMPLE.crt:ro
      - /etc/letsencrypt/live/EXAMPLE/privkey.pem:/config/keys/EXAMPLE.key:ro
      - /srv/nginx/log:/config/log
      - /srv/nginx/doc:/config/www/EXAMPLE_HOST:ro
      - /srv/studlan-EXAMPLE/doc:/config/www/studlan-EXAMPLE:ro
    networks:
      main:
        # TODO add static IP address
        ipv4_address: X.Y.Z.W
    ports:
      - 80:80
      - 443:443
    mem_limit: 1024M
    restart: always
networks:
  # Create this externally as a bridge network with a chosen subnet
  main:
    external: true




























version: '2.4'
services:
  app-bleeding:
    container_name: studlan-app-bleeding
    # TODO use correct image
    image: studlan:bleeding
    environment:
      # TODO add UID+GID
      - STUDLAN_UID=
      - STUDLAN_GID=
      # TODO add superuser info on first run
      - SUPERUSER_USERNAME=
      - SUPERUSER_EMAIL=
      - SUPERUSER_PASSWORD=
      - SUPERUSER_INACTIVE=true
      - FLUSH_DATABASE=false
      - IMPORT_DATABASE=false
      - EXPORT_DATABASE=false
      - NO_START=false
    volumes:
      - /srv/studlan/app-bleeding/settings.py:/srv/studlan/studlan/settings/local.py:ro
      - /srv/studlan/app-bleeding/log:/srv/studlan/log:rw
      # Where to put extracted static files so Nginx can serve them instead
      - /srv/studlan/proxy/docs/static:/srv/studlan/static:rw
      - /srv/studlan/app-bleeding/import_export:/srv/studlan/import_export:rw
    networks:
      - studlan
    restart: "always"
    depends_on:
      - db
  db:
    container_name: studlan-db
    image: postgres
    # postgres doesn't like being run as a specified user, so databse files have a weird owner
    # postgres doesn't write log files by default, so no log dir is bound
    environment:
      - POSTGRES_USER=postgres
      # TODO add superuser password
      - POSTGRES_PASSWORD=
    volumes:
      - /srv/studlan/db/data:/var/lib/postgresql/data:rw
    networks:
      - studlan
    restart: "always"
  proxy:
    container_name: studlan-proxy
    image: linuxserver/nginx
    environment:
      # TODO add UID+GID
      - PUID=
      - PGID=
      - TZ=Europe/Oslo
    volumes:
      - /srv/studlan/proxy/config:/config/nginx:ro
      - /srv/studlan/proxy/log:/config/log:rw
      - /srv/studlan/proxy/docs:/config/www:ro
      # TODO replace with proper certificates once aquired
      - /etc/ssl/certs/ssl-cert-snakeoil.pem:/config/keys/cert.crt:ro
      - /etc/ssl/private/ssl-cert-snakeoil.key:/config/keys/cert.key:ro
    networks:
      - studlan
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app-bleeding
networks:
  studlan:
    # Create: docker network create --driver=bridge studlan
    external: true
