pipeline:
  build:
      image: python:2.7.12
      pull: true
      commands:
        - pip install tox
        - cp studlan/settings/example-local.py studlan/settings/local.py
        - tox

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ devs@causalgaming.no ]
    when:
      status: [ success, changed, failure ]

  docker:
    image: plugins/docker
    repo: registry.fap.no/studlan/studlan
    insecure: true
    tags:
        - master
    when:
        branch: master

  docker:
    image: plugins/docker
    repo: registry.fap.no/studlan/studlan
    insecure: true
    tags:
        - latest
        - $$TAG
    when:
        event: tag

  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    script:
      - docker pull registry.fap.no/studlan/studlan:latest
      - docker-compose -f /srv/docker/studlan/docker-compose.yml stop trondelan lan_recess studlan
      - docker-compose -f /srv/docker/studlan/docker-compose.yml up -d trondelan lan_recess studlan
    when:
        status: success
        event: tag

  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    script:
      - docker pull registry.fap.no/studlan/studlan:master
      - docker-compose -f /srv/docker/studlan/docker-compose.yml stop trondelan_dev
      - docker-compose -f /srv/docker/studlan/docker-compose.yml up -d trondelan_dev
    when:
        status: success
        branch: master
