pipeline:
  test:
    image: python:2.7.12
    pull: true
    commands:
      - pip install tox
      - cp studlan/settings/example-local.py studlan/settings/local.py
      - tox

  docker:
    image: plugins/docker
    repo: studlan/studlan
    registry: localhost:5000
    insecure: true
    debug: true
    tags:
        - master
    when:
        branch: drone_mario

  docker:
    image: plugins/docker
    repo: localhost:5000/studlan
    insecure: true
    tags:
        - latest
        - $$TAG
    when:
        event: tag

  ssh:
    image: appleboy/drone-ssh
    host:
     - mario.causalgaming.no
    user: root
    port: 22
    command_timeout: 1000
    script:
      - docker pull localhost:5000/studlan:latest
      - docker-compose -f /srv/docker/studlan/docker-compose.yml down trondelan studlan
      - docker-compose -f /srv/docker/studlan/docker-compose.yml up -d trondelan studlan
    when:
        status: success
        event: tag

  ssh:
    image: appleboy/drone-ssh
    host:
     - mario.casualgaming.no
    user: root
    port: 22
    command_timeout: 1000
    script:
      - docker pull registry.fap.no/studlan/studlan:master
      - docker-compose -f /srv/docker/studlan/docker-compose.yml down trondelan_dev
      - docker-compose -f /srv/docker/studlan/docker-compose.yml up -d trondelan_dev
    when:
        status: success
        branch: master
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/toodoooo
    channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job :)
      {{else}}
        build {{build.number}} failed. Fix me please :|
      {{/success}}
