build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - cp studlan/settings/example-local.py studlan/settings/local.py
      #- tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

publish:
  docker:
    registry: gengar.l.fap.no:5000
    repo: studlan/studlan
    tag:
        - latest
        - $$TAG
    insecure: true
    when:
        event: tag
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest

  docker:
    registry: gengar.l.fap.no:5000
    repo: studlan/studlan
    tag: master
    insecure: true
    when:
        branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: master

cache:
  mount:
    - docker/image.tar
