build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - cp studlan/settings/example-local.py studlan/settings/local.py
      - tox
      - rm -rf env
      - rm -rf studlan/settings/local.py

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

publish:
  docker:
    registry: gengar.l.fap.no:5000
    repo: studlan/studlan
    tag:
        - latest
        - $$TAG
    insecure: true
    when:
        event: tag

  docker:
    registry: gengar.l.fap.no:5000
    repo: studlan/studlan
    tag: master
    insecure: true
    # when:
    #     branch: master
