build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - cp studlan/settings/example-local.py studlan/settings/local.py
      #- tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

publish:
  docker:
    registry: registry.fap.no
    repo: studlan/studlan
    tag:
        - latest
        - $$TAG
    insecure: true
    when:
        event: tag
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest

  docker:
    registry: registry.fap.no
    repo: studlan/studlan
    tag: master
    insecure: true
    when:
        branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: master

deploy:
  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    sleep: 2
    commands:
      - docker pull registry.fap.no/studlan/studlan:latest
      - docker-compose stop trondelan lan_recess
      - docker-compose up trondelan lan_recess -d
    when:
        event: tag

  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    sleep: 2
    commands:
      - docker pull registry.fap.no/studlan/studlan:master
      - docker-compose stop trondelan_dev
      - docker-compose up trondelan_dev -d
    when:
        branch: master
