build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - cp studlan/settings/example-local.py studlan/settings/local.py
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:

# Deploy prod
  ssh:
    host: onyx.fap.no
    user: www
    port: 22
    when:
        event: tag
    commands:
      - cd /usr/local/www/trondelan.no
      - git fetch --tags
      - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - git pull
      - make env
      - make prod
      - make migrate
      - make collect_static
      - supervisorctl restart uwsgi_trondelan.no

# Deploy dev
  ssh:
    host: onyx.fap.no
    user: www
    port: 22
    when:
        branch: master
    commands:
      - cd /usr/local/www/dev.trondelan.no
      - git checkout master
      - git pull
      - cp -r studlan/settings/example-local.py studlan/settings/local.py
      - make env
      - make prod
      - make migrate
      - make collect_static
      - supervisorctl restart uwsgi_dev.trondelan.no
