# Travis CI config for studlan

# Required env vars:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - DOCKER_REPO

language: python

# virtualenv is implicit for python
python:
  - "2.7"

services:
  - docker

cache: pip

branches:
  only:
  - master
  - buildtools-replacement # TMP

stages:
  - test
  - deploy-registry
  - deploy-site

jobs:
  include:
    # Test
    - stage: test
      name: Validate project
      install: pip install --upgrade -r requirements/test.txt
      before_script: cp sample-configs/local-empty.py studlan/settings/local.py
      script: python manage.py check --deploy --fail-level=ERROR
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      before_script: cp sample-configs/local-empty.py studlan/settings/local.py
      script: python manage.py test

    # Deploy to registry
    - stage: deploy-registry
      name: Deploy stable/versioned to registry
      # Requires tag "vX.Y.Z" without suffix
      if: (branch = master) AND (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      script: manage/deploy-ci.sh stable $TRAVIS_TAG
    - stage: deploy-registry
      name: Deploy bleeding/unversioned to registry
      if: (branch = master) AND NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      script: manage/deploy-ci.sh bleeding
    - stage: deploy-registry # TMP buildtools-replacement untagged
      name: Deploy buildtools-replacement unversioned to registry
      if: (branch = buildtools-replacement) AND NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      script: manage/deploy-ci.sh buildtools-replacement

# TODO deploy to site, jobs cloned from the above
