# Travis CI config for studlan

# Required env vars:
# - DOCKER_USER
# - DOCKER_PASSWORD
# - DOCKER_REPO
# - SSH_USER
# - SSH_HOST

language: python

# virtualenv is implicit for python
python:
  - "2.7"

services:
  - docker

cache: pip

branches:
  only:
  - master
  - buildtools-replacement # TMP

env:
  global:
    # DOCKER_PASSWORD
    - secure: "jlshEhPvcF5bLW4yVyOe08V+ULRzPxAUcPlhPhVRQSlCAGP7yWt3VLrZH/645WvOh41OHi4Ta3XMVxtBIHPpI/QGXYeUCoq02a/4DtvAR6isoGVbMOSzNe0iG664GJgVmck1jkQCoo0QPYt2NLiOy52/Wchx4RtJMR9Ns17tfVmABfhKjxtYR8UuktuSH4i8Cw7pY0IGDxMQzukR4OO3NIQUQS1hOh9nx2yYpe5VdHnoHZLBGVBVMyehxWdZul1hXpEusvk+x7xM7z8EmGwAZ3PKG/GcHI94A3LlnAY9a2sAwDI7Tn+JGA+jUYnhXfgDAMQTjDihzpZl7IpDitebW/OGPAk6WBrPyZK0KUVqIwqmuwdbsQFbiAnIr6UB/1vbretF41Gdx0XOK9QkMismD7hxjDtW9kYSF9hYqHxLycF4NPTSG6/q4G7wpuwlxdBMZsVIAFVgLmeXHReDc192in6YUnGFqB8yNi+5HYO7TRxN0v81kBn01gYhBeX9Q/4bgkG8t1kSdxJDjFw/VwdzTSqwAO/PmK5F2rCb5PrmfSVAoWE6vgKVwE5gQSERkuesjMPgvnc63TFm/3WTfErv71fH3CvGIDKz3T3+j9VVKgFO5nUxkunm5UFkiQff239wpZ/+AchknZ7DvT1R0TIuHtn6zC8UAbCzhcPGww3to38="

stages:
  - test
  - deploy-registry
  - deploy-site

jobs:
  include:
    # Testing stage
    - stage: test
      name: Validate project
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-validate.sh
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-test.sh
    #- stage: test
    #  name: Analyze source code
    #  install: pip install --upgrade -r requirements/test.txt
    #  script: manage/ci-analyze-source.sh

    # Deploy to registry stage
    - stage: deploy-registry
      name: Build and deploy stable/versioned to registry
      # Requires tag "vX.Y.Z" without suffix
      if: (branch = master) AND (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      script: manage/ci-deploy-registry.sh stable $TRAVIS_TAG
    - stage: deploy-registry
      name: Build and deploy bleeding/unversioned to registry
      if: (branch = master) AND NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      script: manage/ci-deploy-registry.sh bleeding
    - stage: deploy-registry # TMP buildtools-replacement untagged
      name: Build and deploy buildtools-replacement unversioned to registry
      if: (branch = buildtools-replacement) AND NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      script: manage/ci-deploy-registry.sh buildtools-replacement

    # Deploy to site stage
    - stage: deploy-site # TMP buildtools-replacement untagged
      name: Deploy buildtools-replacement unversioned to site
      if: NOT (type = cron) AND (branch = buildtools-replacement) AND NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      before_install:
      - openssl aes-256-cbc -K $encrypted_c5d4d3c2a77b_key -iv $encrypted_c5d4d3c2a77b_iv -in keys/studlan.key.enc -out keys/studlan.key -d
      - chmod 600 keys/studlan.key
      install: true # NOP
      script: ssh -oStrictHostKeyChecking=no -i keys/studlan.key ${SSH_USER}@${SSH_HOST} ./deploy-studlan-dev.sh
