# Travis CI config for studlan

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (encrypted)
# - DOCKER_PASSWORD (encrypted)
# - SSH_HOST (encrypted)
# - SSH_USER (encrypted)
# - (automatic encryption keys)

# virtualenv is implicit for python
language: python
python:
  - "2.7"

services:
  - docker

cache: pip

env:
  global:
    # DOCKER_USER
    - secure: "Zod4Zc/Q/jZT5zzE1gaOTP7b/EW8Q4bWcN480h+Asg2X9rxrhO5Mks5cNW5jUcJMnmUIOo1VOuujM3gXvZ5YKVmMvs3DF2m1V2ycCzqsWniQrSB9nMaH1us/mlJeX73ENWgOjmP/QQGl2CSbfVdpW9MUJTlZC7PJD/2fjaCjCo4="
    # DOCKER_PASSWORD
    - secure: "fbddW95d42qdsym8iMmINpyVP+dCJhANUAswMwVE29mMExHdSDPfaTQDJ/lkn2VtIvStaCAcal0wimWf3ckwS8uxyI6++jq6TLx0h3ck71KucY7MKDDx6vjLlKKEk3CJG3ql9I+d9mcUcDj0YgGk/wWtp7KQM8vDTu80rdEesZQ="
    # SSH_HOST
    - secure: "U99c5mot5Wx8GjX1D49EHVGQiiLerWxibxXh3FmHhmZvNq9f3Wkp+xADrPd88tvfWUjTcy40itSy5gK+jcMsVNgzYqnHUcpjHFaOW1GcnhuClnvxN8EodBchxlNThTr7NXGZU6AAdP5wBmuGM8oo0g7u+LYDxRY8X+s9Sncol1c="
    # SSH_USER
    - secure: "jN3wcS8YrcKLJ/MrXiidl3HJb6hDGW33EejxVbkf8msBCiCkQhJPk2NiEsnPNoHvmNQ0AIQbKZkyje8zotKqI3YTaSPAWfe1cPVCBY6wkNCOEpQeEoBEpeCShryX73A4N/ru++IsfGFd65pipVlPe/oBKn2bFPQEz1sznxO9cdc="

stages:
  - test
  - name: deploy-registry
    if: (branch = master) AND NOT (type = pull_request)
  - name: deploy-site
    if: (branch = master) AND NOT (type = pull_request)

jobs:
  include:
    # Testing stage
    - stage: test
      name: Validate Django project
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-validate-django.sh
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-test.sh
    - stage: test
      name: Validate Docker image
      install: true # NOP
      script: manage/ci-validate-docker.sh
    - stage: test
      name: Show outdated dependencies
      install: true # NOP
      script: manage/ci-show-outdated-deps.sh
    #- stage: test
    #  name: Analyze source code
    #  install: pip install --upgrade -r requirements/test.txt
    #  script: manage/ci-analyze-source.sh

    # Deploy to registry stage
    - stage: deploy-registry
      name: Build and deploy stable (versioned) to registry
      # Requires tag "vX.Y.Z" without suffix
      if: (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      script: manage/ci-deploy-registry.sh stable $TRAVIS_TAG
    - stage: deploy-registry
      name: Build and deploy bleeding (unversioned) to registry
      if: NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      script: manage/ci-deploy-registry.sh bleeding

    # Deploy to site stage
    - stage: deploy-site
      name: Deploy stable (versioned) to site
      if: (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      before_install:
      - openssl aes-256-cbc -K $encrypted_974f21a5dc05_key -iv $encrypted_974f21a5dc05_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
      - chmod 600 keys/ssh_deploy.key
      install: true # NOP
      script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} ./deploy-studlan-stable.sh
    - stage: deploy-site
      name: Deploy bleeding (unversioned) to site
      if: NOT (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      before_install:
      - openssl aes-256-cbc -K $encrypted_974f21a5dc05_key -iv $encrypted_974f21a5dc05_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
      - chmod 600 keys/ssh_deploy.key
      install: true # NOP
      script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} ./deploy-studlan-bleeding.sh
