# Travis CI config for studlan

# Required env vars:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - DOCKER_REPO

language: python

# virtualenv is implicit for python
python:
  - "2.7"

services:
  - docker

cache: pip

branches:
  only:
  - master
  - buildtools-replacement # TMP

stages:
  - test
  - deploy-registry
  - deploy-site

jobs:
  include:
    # Test
    - stage: test
      name: Validate project
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py check --deploy --fail-level=ERROR
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py test

    # Deploy to registry
    - stage: deploy-registry
      name: Deploy bleeding/unversioned to registry
      if: (branch = master) AND NOT (tag =~ ^v[0-9])
      install: echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
      script: docker build -t $DOCKER_REPO:bleeding .
      deploy: docker push $DOCKER_REPO:bleeding
    - stage: deploy-registry
      name: Deploy stable/versioned to registry
      if: (branch = master) AND (tag =~ ^v[0-9])
      install: echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
      script: docker build -t $DOCKER_REPO:stable .
      before_deploy: docker tag $DOCKER_REPO:stable $DOCKER_REPO:$TRAVIS_TAG
      deploy:
        - docker push $DOCKER_REPO:stable
        - docker push $DOCKER_REPO:$TRAVIS_TAG
    - stage: deploy-registry # TMP buildtools-replacement untagged
      name: Deploy buildtools-replacement unversioned to registry
      if: (branch = buildtools-replacement) AND NOT (tag =~ ^v[0-9])
      install: echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
      script: docker build -t $DOCKER_REPO:buildtools-replacement .
      deploy: docker push $DOCKER_REPO:buildtools-replacement

# TODO deploy to site, jobs cloned from the above
