# Travis CI config for studlan

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (secure)
# - DOCKER_PASSWORD (secure)
# - SONARCLOUD_TOKEN (secure)
# - SONARCLOUD_ORG
# - SSH_HOST
# - SSH_USER
# - (automatic encryption keys) (secure)

# virtualenv is implicit for python
language: python
python:
  - "2.7"

services:
  - docker

cache: pip

stages:
  - name: test
  - name: deploy-registry
    if: type = push
  - name: deploy-site
    if: type = push

jobs:
  include:
    # Stage: Testing
    - stage: test
      name: Validate Django project
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-validate-django.sh
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: manage/ci-test.sh
    - stage: test
      name: Analyze source code (flake8)
      install: pip install --upgrade -r requirements/test.txt
      script: flake8
      # This does not fail the build if the SonarCloud quality gate fails,
      # but SonarCloud has a GitHub PR status check which can be made required.
    - stage: test
      name: Analyze source code (SonarCloud)
      language: java
      addons:
        sonarcloud:
          organization: $SONARCLOUD_ORG
          token: $SONARCLOUD_TOKEN
      git:
        depth: false
      script: sonar-scanner
    - stage: test
      name: Validate Docker image
      install: true # NOP
      before_script: echo "v0.0.0-SNAPSHOT" > VERSION
      script: manage/ci-validate-docker.sh

    # Stage: Deploy to registry
    - stage: deploy-registry
      name: Build and deploy stable to registry
      # Requires tag "vX.Y.Z" without suffix
      if: (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install: true # NOP
      before_script: echo "$TRAVIS_TAG" > VERSION
      script: manage/ci-deploy-registry.sh stable $TRAVIS_TAG
    - stage: deploy-registry
      name: Build and deploy bleeding to registry
      if: (branch = master)
      install: true # NOP
      before_script: echo "v0.0.0-SNAPSHOT+$(TZ=Etc/GMT date "+%Y-%m-%dT%H:%M:%SZ")" > VERSION
      script: manage/ci-deploy-registry.sh bleeding

    # Stage: Deploy to site(s)
    - stage: deploy-site
      name: Build and deploy stable to server
      # Requires tag "vX.Y.Z" without suffix
      if: (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$)
      install:
      - openssl aes-256-cbc -K $encrypted_974f21a5dc05_key -iv $encrypted_974f21a5dc05_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
      - chmod 600 keys/ssh_deploy.key
      script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} stable
    - stage: deploy-site
      name: Build and deploy bleeding to server
      if: (branch = master)
      install:
      - openssl aes-256-cbc -K $encrypted_974f21a5dc05_key -iv $encrypted_974f21a5dc05_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
      - chmod 600 keys/ssh_deploy.key
      script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} bleeding
