# Travis CI config for studlan

# Required env vars:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - DOCKER_REPO

language: python

# virtualenv is implicit for python
python:
  - "2.7"

services:
  - docker

cache: pip

stages:
  - test
  - deploy-registry
  - deploy-site

jobs:
  include:
    # Test
    - stage: test
      name: Validate project
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py check --deploy --fail-level=ERROR
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py test

    # Deploy to registry
    - stage: deploy-registry
      name: Deploy bleeding/untagged to registry
      if: (branch = master) AND (tag IS absent)
      script: manage/deploy-travis.sh bleeding
    - stage: deploy-registry
      name: Deploy stable/tagged to registry
      if: (branch = master) AND (tag IS present)
      script: manage/deploy-travis.sh "$TRAVIS_TAG" stable
    - stage: deploy-registry
      name: Deploy bleeding/untagged to registry (buildtools-replacement)
      if: (branch = buildtools-replacement) AND (tag IS absent)
      script: manage/deploy-travis.sh buildtools-replacement-bleeding
    - stage: deploy-registry
      name: Deploy stable/tagged to registry (buildtools-replacement)
      if: (branch = buildtools-replacement) AND (tag IS present)
      script: manage/deploy-travis.sh buildtools-replacement-"$TRAVIS_TAG" buildtools-replacement-stable

#    # Deploy to site
#    - stage: deploy-site
#      name: Deploy bleeding to site
#      if: (branch = master) AND (tag IS absent)
#      script: echo bleeding deploy WIP
#    - stage: deploy-site
#      name: Deploy stable to site
#      if: (branch = master) AND (tag IS present)
#      script: echo stable deploy WIP
#    - stage: deploy-site
#      name: Deploy buildtools-replacement to site
#      if: branch = buildtools-replacement
#      script: echo buildtools-replacement deploy WIP
