# Travis CI config for studlan

# Required env vars:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - DOCKER_REPO

language: python

# virtualenv is implicit for python
python:
  - "2.7"

services:
  - docker

stages:
  - test
  - build
  - deploy-registry
  - deploy-site

jobs:
  include:
    # Test
    - stage: test
      name: Validate
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py check --deploy --fail-level=ERROR
    - stage: test
      name: Run tests
      install: pip install --upgrade -r requirements/test.txt
      script: python manage.py test

    # Build
    - stage: build
      name: Build Docker image
      script: docker build -t studlan:dev .

    # Deploy to registry
    - stage: deploy-registry
      name: Deploy bleeding to registry
      if: branch = master
      install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker tag studlan:dev studlan:bleeding && docker push $DOCKER_REPO:bleeding
    - stage: deploy-registry
      name: Deploy latest to registry
      if: branch = latest
      install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker tag studlan:dev studlan:bleeding && docker push $DOCKER_REPO:latest
    - stage: deploy-registry
      name: Deploy buildtools-replacement to registry
      if: branch = buildtools-replacement
      install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker tag studlan:dev studlan:bleeding && docker push $DOCKER_REPO:buildtools-replacement

    # Deploy to site
    - stage: deploy-site
      name: Deploy bleeding to site
      if: branch = master
      script: echo bleeding deploy WIP
    - stage: deploy-site
      name: Deploy latest to site
      if: branch = latest
      script: echo latest deploy WIP
    - stage: deploy-site
      name: Deploy buildtools-replacement to site
      if: branch = buildtools-replacement
      script: echo buildtools-replacement deploy WIP
