# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0008_auto_20160205_1537'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='relevant_to',
            field=models.ManyToManyField(blank=True, to='lan.LAN'),
        ),
    ]
