# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0010_auto_20170925_2301'),
        ('news', '0003_article_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_to', models.ManyToManyField(blank=True, to='lan.LAN')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'nb', 'Norsk'), (b'en', 'English')], max_length=15, verbose_name='language')),
                ('translated_title', models.CharField(max_length=50, verbose_name=b'title')),
                ('translated_body', models.TextField(verbose_name=b'body')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.FAQ', verbose_name=b'FAQ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_to', models.ManyToManyField(blank=True, to='lan.LAN')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToParentsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'nb', 'Norsk'), (b'en', 'English')], max_length=15, verbose_name='language')),
                ('translated_title', models.CharField(max_length=50, verbose_name=b'title')),
                ('translated_body', models.TextField(verbose_name=b'body')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.ToParents', verbose_name=b'ToParents')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
