# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_faq_faqtranslation_toparents_toparentstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'published'),
        ),
        migrations.AddField(
            model_name='toparents',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'published'),
        ),
    ]
