# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date published'),
        ),
    ]
