# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-08 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_auto_20180910_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='require_alias',
            field=models.BooleanField(default=False, help_text=b'If checked, players will need to register an alias for the Activity that the competition belongs to.', verbose_name=b'require alias'),
        ),
    ]
