# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_auto_20190308_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['status'], 'permissions': (('manage', 'Manage compos and matches'),)},
        ),
    ]
