# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_auto_20190401_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='challonge_url',
            field=models.CharField(blank=True, help_text=b'Do not set this field if challonge integration is enabled. The challonge url will be generated after starting the competition.', max_length=50, null=True, verbose_name=b'Challonge url'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tournament_format',
            field=models.CharField(blank=True, choices=[(b'single elimination', b'Single elimination'), (b'double elimination', b'Double elimination')], help_text=b'Only set this field if the Challonge integration is being used for this competition.', max_length=20, null=True, verbose_name=b'Tournament format'),
        ),
    ]
