# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_auto_20190730_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['status'], 'permissions': (('manage', 'Manage compos and matches'),), 'verbose_name': 'competition', 'verbose_name_plural': 'competitions'},
        ),
        migrations.AlterModelOptions(
            name='competitiontranslation',
            options={'verbose_name': 'competition translation', 'verbose_name_plural': 'competition translations'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'competition match', 'verbose_name_plural': 'competition matches'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['user', 'team'], 'verbose_name': 'competition participant', 'verbose_name_plural': 'competition participants'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.CharField(blank=True, help_text='Use a mirrored image of at least a height of 150px.', max_length=100, verbose_name='image URL'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Activity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='challonge_url',
            field=models.CharField(blank=True, help_text=b'Do not set this field if challonge integration is enabled. The challonge url will be generated after starting the competition.', max_length=50, null=True, verbose_name='Challonge URL'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_match_points',
            field=models.SmallIntegerField(default=1, help_text='This number represents how many points are needed to win a match. E.g. 3 in a BO 5 or 16 in BO 30', verbose_name='maximum match points'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.SmallIntegerField(default=0, help_text='The maximum number of participants allowed for a competition. Restricts participants based on competition type. 0 means infinite participants are allowed.', verbose_name='maximum participants'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='require_alias',
            field=models.BooleanField(default=False, help_text='If checked, players will need to register an alias for the activity that the competition belongs to.', verbose_name='require alias'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Registration open'), (2, 'Registration closed'), (3, 'In progress'), (4, 'Finished')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='team_size',
            field=models.IntegerField(blank=True, default=5, verbose_name='team size'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tournament_format',
            field=models.CharField(blank=True, choices=[(b'single elimination', 'Single elimination'), (b'double elimination', 'Double elimination')], help_text=b'Only set this field if the Challonge integration is being used for this competition.', max_length=20, null=True, verbose_name='tournament format'),
        ),
        migrations.AlterField(
            model_name='competitiontranslation',
            name='translated_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition', verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='final_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='final score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchid',
            field=models.CharField(max_length=50, verbose_name='match ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_reg_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='p1 reg score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_reg_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='p2 reg score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='competition.Participant', verbose_name='player 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='competition.Participant', verbose_name='player 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='competition.Participant', verbose_name='winner'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cid'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition', verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
