# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Registration open'), (2, 'Registration closed'), (3, 'In progress'), (4, 'Finished')], verbose_name='status'),
        ),
    ]
