# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_auto_20190730_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'In progress'), (4, 'Finished')], verbose_name='status'),
        ),
    ]
