# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_auto_20190728_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.SmallIntegerField(default=0, help_text='The maximum number of participants allowed for a competition. Restricts participants based on competition type. 0 means infinite participants are allowed.', verbose_name='maximum participants'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='require_alias',
            field=models.BooleanField(default=False, help_text='If checked, players will need to register an alias for the activity that the competition belongs to.', verbose_name='require alias'),
        ),
    ]
