# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lan', '0008_auto_20160205_1537'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='attendee',
            index_together=set([('user', 'lan')]),
        ),
        migrations.AlterIndexTogether(
            name='ticket',
            index_together=set([('user', 'ticket_type')]),
        ),
    ]
