# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0008_auto_20160205_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='priority',
            field=models.IntegerField(default=0, help_text=b'In what priority the tickets will show, higher number will show first.', verbose_name=b'Prioity'),
        ),
    ]
