# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0010_auto_20170925_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lan',
            options={'ordering': ['start_date'], 'permissions': (('export_paying_participants', 'Can export list of paying participants to downloadable file'), ('register_arrivals', 'Can register arrivals'), ('register_new_user', 'Can directly register a new user'))},
        ),
    ]
