# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0013_auto_20190721_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='visible_title',
            field=models.CharField(blank=True, help_text=b'Title to show above stream. May be empty.', max_length=100, verbose_name=b'visible title'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, help_text=b'Short description that will show on front page.', verbose_name=b'description'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='link',
            field=models.CharField(help_text=b'Link to the embedding stream.', max_length=300, verbose_name=b'link'),
        ),
    ]
