# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0014_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='map_link',
            field=models.CharField(blank=True, help_text='URL for an embedded map.', max_length=300, verbose_name='map link'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='video_link',
            field=models.CharField(blank=True, help_text='URL for an embedded video.', max_length=300, verbose_name='video link'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='When the tickets will be made available.', verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
    ]
