# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0015_auto_20190730_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lan',
            name='video_link',
        ),
        migrations.AddField(
            model_name='lan',
            name='media_link',
            field=models.CharField(blank=True, help_text='URL for embedded media.', max_length=300, verbose_name='media link'),
        ),
        migrations.AddField(
            model_name='lan',
            name='media_type',
            field=models.CharField(choices=[(b'image', 'Image'), (b'video', 'Video'), (b'stream', 'Stream')], default=b'image', help_text='Type of the optional embedded media.', max_length=10, verbose_name='media type'),
        ),
    ]
