# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0020_auto_20200909_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='allow_manual_payment',
            field=models.BooleanField(default=False, verbose_name='allow manual payment'),
        ),
    ]
