# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 11:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0021_lan_allow_manual_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='rules_link',
            field=models.CharField(blank=True, help_text='URL to rules which users have to accept to buy tickets.', max_length=300, verbose_name='rules link'),
        ),
    ]
