# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 11:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0022_lan_rules_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='priority',
            field=models.IntegerField(default=0, help_text='In what priority the tickets will show, higher number will show first.', verbose_name='priority'),
        ),
    ]
