# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 15:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0024_auto_20220803_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='schedule_link',
            field=models.CharField(blank=True, help_text='URL to an alternative schedule page.', max_length=300, verbose_name='schedule link'),
        ),
    ]
