# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_remove_sponsor_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'sponsor', 'verbose_name_plural': 'sponsors'},
        ),
        migrations.AlterModelOptions(
            name='sponsorrelation',
            options={'ordering': ['-priority'], 'verbose_name': 'sponsor relation', 'verbose_name_plural': 'sponsor relations'},
        ),
        migrations.AlterModelOptions(
            name='sponsortranslation',
            options={'verbose_name': 'sponsor translation', 'verbose_name_plural': 'sponsor translations'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='banner',
            field=models.CharField(blank=True, help_text='Use a mirrored image of at least a height of 150px.', max_length=100, verbose_name='banner URL'),
        ),
        migrations.AlterField(
            model_name='sponsorrelation',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='lan'),
        ),
        migrations.AlterField(
            model_name='sponsorrelation',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor', verbose_name='sponsor'),
        ),
    ]
