# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorrelation',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
        migrations.AlterField(
            model_name='sponsorrelation',
            name='priority',
            field=models.IntegerField(help_text='Higher priority means closer to the top of the sponsor list.', verbose_name='priority'),
        ),
    ]
