# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_auto_20200203_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorRelationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'nb', 'Norsk'), (b'en', 'English')], max_length=15, verbose_name='language')),
                ('description', models.TextField(verbose_name='description')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sponsor.SponsorRelation', verbose_name=b'partner relation')),
            ],
            options={
                'verbose_name': 'partner relation translation',
                'verbose_name_plural': 'partner relation translations',
            },
        ),
        migrations.AlterField(
            model_name='sponsortranslation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sponsor.Sponsor', verbose_name=b'partner'),
        ),
    ]
