# Example Docker Compose config for Nginx reverse proxy and web server

# This example uses extarnal networks and static IPs, to make firewall and external Nginx config easier.

version: "2.4"
services:
  nginx-master:
    image: linuxserver/nginx
    container_name: nginx-master
    environment:
      # TODO add UID+GID of nginx host user
      - PUID=
      - PGID=
      - TZ=Europe/Oslo
    volumes:
      - /srv/nginx/config:/config/nginx:ro
      # TODO Add certs for all served domains, or use snakeoil ones temporarily
      #- /etc/ssl/certs/ssl-cert-snakeoil.pem:/config/keys/EXAMPLE.crt:ro
      #- /etc/ssl/private/ssl-cert-snakeoil.key:/config/keys/EXAMPLE.key:ro
      - /etc/letsencrypt/live/EXAMPLE/fullchain.pem:/config/keys/EXAMPLE.crt:ro
      - /etc/letsencrypt/live/EXAMPLE/privkey.pem:/config/keys/EXAMPLE.key:ro
      - /srv/nginx/log:/config/log
      - /srv/nginx/doc:/config/www/EXAMPLE_HOST:ro
      - /srv/studlan-EXAMPLE/doc:/config/www/studlan-EXAMPLE:ro
    networks:
      main:
        # TODO add static IP address
        ipv4_address: X.Y.Z.W
    ports:
      # Alternatively, just port forward (firewall-style) to make source IP addresses correct
      - 80:80
      - 443:443
    mem_limit: 1024M
    restart: always
networks:
  # Create this externally as a bridge network with a chosen subnet
  main:
    external: true
