# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20190730_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'team invitation', 'verbose_name_plural': 'team invitations'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['user'], 'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['tag', 'title'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='invitee'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newteamleader', to=settings.AUTH_USER_MODEL, verbose_name='leader'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='new_team_members', through='team.Member', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
