# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 11:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0006_auto_20191008_0142'),
        ('competition', '0019_auto_20191007_0818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lan', '0015_auto_20190730_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('send_mail', 'Can send mails to users'),),
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.UUIDField(blank=True, help_text='To prevent sending the same mail twice.', null=True, verbose_name='form id')),
                ('sent_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time sent')),
                ('subject', models.CharField(max_length=80, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('recipient_everyone', models.BooleanField(default=False, help_text='Pinned articles are shown before non-pinned ones.', verbose_name='recipient everyone')),
                ('recipients_total', models.IntegerField(default=0, help_text='Sum of all unique users that should receive the mail.', verbose_name='total number of recipients')),
                ('successful_mails', models.IntegerField(default=0, help_text='How many of the mails were sent successfully.', verbose_name='successful mails')),
                ('failed_mails', models.IntegerField(default=0, help_text='How many of the mails were not sent because of some failure.', verbose_name='failed mails')),
                ('done_sending', models.BooleanField(default=False, help_text='If all mails have been attempted sent.', verbose_name='done sending')),
                ('recipient_competitions', models.ManyToManyField(blank=True, to='competition.Competition', verbose_name='recipient competitions')),
                ('recipient_lans', models.ManyToManyField(blank=True, to='lan.LAN', verbose_name='recipient LANs')),
                ('recipient_teams', models.ManyToManyField(blank=True, to='team.Team', verbose_name='recipient teams')),
                ('recipient_tickets', models.ManyToManyField(blank=True, to='lan.TicketType', verbose_name='recipient tickets')),
                ('recipient_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='recipient users')),
            ],
            options={
                'ordering': ['-sent_time'],
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
            },
        ),
    ]
