# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='done_sending',
            field=models.BooleanField(default=False, help_text='If all mails have been attempted sent.', verbose_name='done sending'),
        ),
        migrations.AddField(
            model_name='mail',
            name='failed_mails',
            field=models.IntegerField(default=0, help_text='How many of the mails were not sent because of some failure.', verbose_name='failed mails'),
        ),
        migrations.AddField(
            model_name='mail',
            name='recipients_total',
            field=models.IntegerField(default=0, help_text='Sum of all unique users that should receive the mail.', verbose_name='total number of recipients'),
        ),
        migrations.AddField(
            model_name='mail',
            name='successful_mails',
            field=models.IntegerField(default=0, help_text='How many of the mails were sent successfully.', verbose_name='successful mails'),
        ),
    ]
