# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-24 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='recipient_competitions',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient_lans',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient_teams',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient_tickets',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient_users',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
