# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-26 03:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendmail', '0002_auto_20220524_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('uuid', models.UUIDField(help_text='UUID specified by the sender, prevents accidentally sending same mail multiple times.', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time sent')),
                ('language', models.CharField(max_length=100, verbose_name='language')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
            },
        ),
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(blank=True, help_text='Time the email was sent. Unset if not sent yet.', null=True, verbose_name='time sent')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sendmail.Mail', verbose_name='mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-sent_time'],
                'verbose_name': 'mail recipient',
                'verbose_name_plural': 'mail recipients',
            },
        ),
        migrations.AlterModelOptions(
            name='sendmail',
            options={'managed': False, 'permissions': (('list', 'Can list mails'), ('view', 'Can view mails'), ('send', 'Can send mails'))},
        ),
    ]
