# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20200216_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='form_id',
            field=models.UUIDField(blank=True, help_text='To prevent sending the same mail twice.', null=True, verbose_name='form id'),
        ),
    ]
