# Version 3.3 because of the Travis image
version: '3.3'

services:
  studlan:
    container_name: studlan-test-app
    image: studlan
    build:
      context: ..
    environment:
      # Dummy UID+GID
      - STUDLAN_UID=123
      - STUDLAN_GID=123
      - SUPERUSER_USERNAME=batman
      - SUPERUSER_EMAIL=batman@localhost
      - SUPERUSER_PASSWORD=manbat
      - SUPERUSER_INACTIVE=false
      - FLUSH_DATABASE=true
      - IMPORT_DATABASE=true
      - EXPORT_DATABASE=true
      # Don't start the server
      - NO_START=true
    volumes:
      - ../.local/docker-ci/local.py:/srv/studlan/studlan/settings/local.py:ro
      - ../.local/docker-ci/db:/srv/studlan/db:rw
      - ../.local/docker-ci/log:/srv/studlan/log:rw
    ports:
      - "8080:8080"
