# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lan', '0015_auto_20190730_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='LANTicketPurchaseLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchase_lock', to='lan.LAN', verbose_name='lan')),
            ],
            options={
                'verbose_name': 'LAN ticket purchase lock',
                'verbose_name_plural': 'LAN ticket purchase locks',
            },
        ),
    ]
