# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottery',
            options={'permissions': (('draw', 'Can draw winners'),), 'verbose_name_plural': 'Lotteries'},
        ),
    ]
