# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20190401_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotteryparticipant',
            name='has_won',
        ),
        migrations.AlterField(
            model_name='lotteryparticipant',
            name='lottery',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery'),
        ),
        migrations.AlterField(
            model_name='lotteryparticipant',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='lottery',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
