# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20190725_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottery',
            options={'permissions': (('draw', 'Can draw winners'),), 'verbose_name': 'lottery', 'verbose_name_plural': 'lotteries'},
        ),
        migrations.AlterModelOptions(
            name='lotteryparticipant',
            options={'verbose_name': 'lottery participant', 'verbose_name_plural': 'lottery participants'},
        ),
        migrations.AlterModelOptions(
            name='lotterytranslation',
            options={'verbose_name': 'lottery translation', 'verbose_name_plural': 'lottery translations'},
        ),
        migrations.AlterModelOptions(
            name='lotterywinner',
            options={'verbose_name': 'lottery winner', 'verbose_name_plural': 'lottery winners'},
        ),
        migrations.AlterField(
            model_name='lottery',
            name='multiple_winnings',
            field=models.BooleanField(default=False, help_text='Allows a user to win more than one time.', verbose_name='multiple winnings'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='open'),
        ),
        migrations.AlterField(
            model_name='lotteryparticipant',
            name='lottery',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery', verbose_name='lottery'),
        ),
        migrations.AlterField(
            model_name='lotteryparticipant',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='lottery',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery', verbose_name='lottery'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
