# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lan.LAN', verbose_name='LAN'),
        ),
    ]
