# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_auto_20190801_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottery',
            options={'permissions': (('draw', 'Can draw winners'), ('open_close', 'Can open and close lotteries')), 'verbose_name': 'lottery', 'verbose_name_plural': 'lotteries'},
        ),
    ]
