# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_auto_20190814_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='enforce_payment',
            field=models.BooleanField(default=False, help_text='Require users to have paid for the LAN in order to participate.', verbose_name='enforce payment'),
        ),
    ]
