# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20161209_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'created'),
        ),
    ]
