# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20170916_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertoken',
            options={'verbose_name': 'register token', 'verbose_name_plural': 'register tokens'},
        ),
    ]
