# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20160406_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliastype',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alias_type', to='competition.Activity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alias',
            name='nick',
            field=models.CharField(max_length=40, verbose_name=b'nick'),
            preserve_default=True,
        ),
    ]
