# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_competition_tournament_format'),
        ('userprofile', '0007_auto_20161202_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliastype',
            name='activity',
        ),
        migrations.AddField(
            model_name='aliastype',
            name='activity',
            field=models.ManyToManyField(related_name='alias_type', to='competition.Activity'),
        ),
    ]
