# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20170210_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ntnu_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wants_to_sit_with',
        ),
    ]
