# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20170916_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick',
            field=models.CharField(db_index=True, help_text=b'Specify a nick name (display name).', max_length=20, verbose_name='nick'),
        ),
    ]
