# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20170916_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('show_private_info', 'Can show private user info'),)},
        ),
    ]
