# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 17:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20190401_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name': 'user alias', 'verbose_name_plural': 'user aliases'},
        ),
        migrations.AlterModelOptions(
            name='aliastype',
            options={'verbose_name': 'user alias type', 'verbose_name_plural': 'user alias types'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('show_private_info', 'Can show private user info'),), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='alias',
            name='alias_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.AliasType', verbose_name='alias type'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='nick',
            field=models.CharField(max_length=40, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='aliastype',
            name='activity',
            field=models.ManyToManyField(related_name='alias_type', to='competition.Activity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='aliastype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='aliastype',
            name='profile_url',
            field=models.URLField(blank=True, help_text='URL prefix where profile info can be retrieved. E.g. https://steamcommunity.com/id/', null=True, verbose_name='profile URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=4, verbose_name='zip code'),
        ),
    ]
