# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20190728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=4, verbose_name='postal code'),
        ),
    ]
