# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-01 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_userprofile_marketing_optin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='marketing_optin',
            field=models.BooleanField(default=False, help_text='Receive emails about upcoming LANs and stuff.', verbose_name='marketing opt-in'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick',
            field=models.CharField(db_index=True, help_text='Your display name. Should be equal or similar to your username.', max_length=20, verbose_name='nick'),
        ),
    ]
