# # Required secrets:
# # - DOCKER_USERNAME
# # - DOCKER_PASSWORD

# name: CI/CD (release)

# env:
#   DOCKER_IMAGE: casualgaming/studlan

# on:
#   release:
#     types: [published]
#   workflow_dispatch: {}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Build
#         uses: docker/build-push-action@v2
#         with:
#           push: false
#           tags: ${{ env.DOCKER_IMAGE }}:latest

#   publish:
#     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{ env.DOCKER_IMAGE }}:latest
