name: CI/CD (validate)

env:
  PYTHON_VERSION: 2.7

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   Required?
      # - name: Cache dependencies
      #   TODO
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
      - name: Install requirements
        run: pip install -r requirements/test.txt
      - name: Validate Django project
        run: manage/ci/validate-django.sh
      - name: Test
        run: manage/ci/test.sh
      - name: Lint
        run: flake8
      - name: Validate Docker image
        run: manage/ci/validate-docker.sh

yolo
